// <auto-generated />
namespace Kutuphane.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inital2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inital2));
        
        string IMigrationMetadata.Id
        {
            get { return "202210221738513_inital-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
